CREATE DATABASE IF NOT EXISTS test;
USE test;
DROP TABLE IF EXISTS t,mv;
CREATE TABLE t(
	id int AUTO_INCREMENT PRIMARY KEY,
	val int NOT NULL
);
CREATE TABLE mv (
	id INT PRIMARY KEY,
	val_avg decimal(8,4) NOT NULL
);
